language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - ./gradlew check --stacktrace
after_success:
  - ./travis.sh deploy
  - ./travis.sh sonarqube

